FROM armindocachada/tensorflow2-opencv4-raspberrypi4:2.2_4.5.0

# Set the working directory
WORKDIR /work

# Add the data
#COPY . /work
#RUN chmod +x /work/run.sh
# Add python-script

#RUN ls 
ENTRYPOINT ["/work/run.sh" , "/work"]
