FROM sina88/opencv-python3:rpi4

# Set the working directory
WORKDIR /work

RUN ls
#ADD split.py /work
#ADD 20-20000.mp4 /work
#ADD split.py /work
#ADD run.sh /work

#RUN chmod +x /work/run.sh

ENTRYPOINT ["/work/run.sh", "20-20000.mp4" , "data-20-20000"]

#ENTRYPOINT ["python", "/work/split.py", "/work/20-20000.mp4" , "data-20-20000"]

